welcome:
  message: P4D

spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
  datasource:
    url: jdbc:mysql://localhost:3306/habib
    username: root
    password: 12345678

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#  jpa:
#    hibernate:
#      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

#      naming:
#        physical-strategy=org: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

uploads: src/main/resources/static/uploads/



